spring.application.name=AssessmentTrackerSystem

#spring.datasource.url=jdbc:postgresql://localhost:5432/AssessmentTrackerSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/Casestudy
spring.datasource.username=postgres
spring.datasource.password=Sandhya$2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081





